// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUZzfkj8sReMb3zwWTJoz_f9IkiZW1Etk',
    appId: '1:602292274608:web:ff4d5c1ace67985d1c0275',
    messagingSenderId: '602292274608',
    projectId: 'shop-sergipe',
    authDomain: 'shop-sergipe.firebaseapp.com',
    databaseURL: 'https://shop-sergipe-default-rtdb.firebaseio.com',
    storageBucket: 'shop-sergipe.appspot.com',
    measurementId: 'G-BCQZBJ7QCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3gZDaU8SE4d8_jfSPj7p2UT55pLKE62c',
    appId: '1:602292274608:android:ef024d1594a65f411c0275',
    messagingSenderId: '602292274608',
    projectId: 'shop-sergipe',
    databaseURL: 'https://shop-sergipe-default-rtdb.firebaseio.com',
    storageBucket: 'shop-sergipe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW3J9OBqZVwYSPRsmgKcUpSXBGRQgSAiw',
    appId: '1:602292274608:ios:20b6ed4b920990401c0275',
    messagingSenderId: '602292274608',
    projectId: 'shop-sergipe',
    databaseURL: 'https://shop-sergipe-default-rtdb.firebaseio.com',
    storageBucket: 'shop-sergipe.appspot.com',
    iosClientId: '602292274608-g61uktl0p8kb38ij8168rnji03j881nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sergipeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW3J9OBqZVwYSPRsmgKcUpSXBGRQgSAiw',
    appId: '1:602292274608:ios:20b6ed4b920990401c0275',
    messagingSenderId: '602292274608',
    projectId: 'shop-sergipe',
    databaseURL: 'https://shop-sergipe-default-rtdb.firebaseio.com',
    storageBucket: 'shop-sergipe.appspot.com',
    iosClientId: '602292274608-g61uktl0p8kb38ij8168rnji03j881nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sergipeShop',
  );
}
